### ISSUE TITLE
Create a Toggle Button to switch from dark mode to light and vice-versa

### ISSUE THREAD

**Issue by hanshal101** [hanshal101/FirstContrib#4]
All the frontend code is on _/src_ folder fell free to contribute 

The Toggle button should look like this (some what similiar)
![image](https://github.com/hanshal101/FirstContrib/assets/122217807/5e0e781b-6917-4f77-87c6-c26e5b4519d7)

**Comment by rushabh-exe** [comment]
I have solved this issue and made a pr

**Comment by hanshal101** [comment]
ok Thanks
