### ISSUE TITLE
Add Custom Radio button

### ISSUE THREAD

**Issue by hanshal101** [hanshal101/FirstContrib#5]
All the frontend code is located on _/src_ folder.

The Button should look and work somewhat like:
![image](https://github.com/hanshal101/FirstContrib/assets/122217807/c3602b5d-3c41-4f5c-b103-f72a81ffa9ae)

**Comment by rushabh-exe** [comment]
Please assign me. I will do this task.

**Comment by rushabh-exe** [comment]
I have solved this issue already and made a pr

**Comment by hanshal101** [comment]
Ok
